# Alert rules for Bazar Marketplace

groups:
  - name: bazar-alerts
    rules:
      # High-level service alerts
      - alert: ServiceDown
        expr: up == 0
        for: 1m
        labels:
          severity: critical
        annotations:
          summary: "Service {{ $labels.job }} is down"
          description: "{{ $labels.job }} has been down for more than 1 minute."

      - alert: HighErrorRate
        expr: |
          (
            rate(nginx_http_requests_total{status=~"5.."}[5m]) /
            rate(nginx_http_requests_total[5m])
          ) > 0.05
        for: 2m
        labels:
          severity: warning
        annotations:
          summary: "High error rate detected"
          description: "Error rate is {{ $value | humanizePercentage }} for the last 5 minutes."

      # System resource alerts
      - alert: HighCPUUsage
        expr: 100 - (avg by(instance) (irate(node_cpu_seconds_total{mode="idle"}[5m])) * 100) > 80
        for: 2m
        labels:
          severity: warning
        annotations:
          summary: "High CPU usage on {{ $labels.instance }}"
          description: "CPU usage is {{ $value }}% on {{ $labels.instance }}"

      - alert: HighMemoryUsage
        expr: |
          (
            (node_memory_MemTotal_bytes - node_memory_MemAvailable_bytes) /
            node_memory_MemTotal_bytes
          ) * 100 > 90
        for: 2m
        labels:
          severity: warning
        annotations:
          summary: "High memory usage on {{ $labels.instance }}"
          description: "Memory usage is {{ $value }}% on {{ $labels.instance }}"

      - alert: HighDiskUsage
        expr: |
          (
            (node_filesystem_size_bytes{fstype!~"tmpfs|fuse.lxcfs"} -
             node_filesystem_avail_bytes{fstype!~"tmpfs|fuse.lxcfs"}) /
            node_filesystem_size_bytes{fstype!~"tmpfs|fuse.lxcfs"}
          ) * 100 > 85
        for: 2m
        labels:
          severity: warning
        annotations:
          summary: "High disk usage on {{ $labels.instance }}"
          description: "Disk usage is {{ $value }}% on {{ $labels.instance }} mount {{ $labels.mountpoint }}"

      # Database alerts
      - alert: MySQLDown
        expr: mysql_up == 0
        for: 1m
        labels:
          severity: critical
        annotations:
          summary: "MySQL is down"
          description: "MySQL instance {{ $labels.instance }} has been down for more than 1 minute."

      - alert: MySQLSlowQueries
        expr: rate(mysql_global_status_slow_queries[5m]) > 5
        for: 2m
        labels:
          severity: warning
        annotations:
          summary: "High number of slow MySQL queries"
          description: "{{ $value }} slow queries per second on {{ $labels.instance }}"

      - alert: MySQLConnections
        expr: mysql_global_status_threads_connected > 150
        for: 2m
        labels:
          severity: warning
        annotations:
          summary: "High number of MySQL connections"
          description: "{{ $value }} connections on {{ $labels.instance }}"

      - alert: MySQLReplicationLag
        expr: mysql_slave_seconds_behind_master > 30
        for: 1m
        labels:
          severity: warning
        annotations:
          summary: "MySQL replication lag"
          description: "MySQL slave is {{ $value }} seconds behind master on {{ $labels.instance }}"

      # Redis alerts
      - alert: RedisDown
        expr: redis_up == 0
        for: 1m
        labels:
          severity: critical
        annotations:
          summary: "Redis is down"
          description: "Redis instance {{ $labels.instance }} has been down for more than 1 minute."

      - alert: RedisMemoryUsage
        expr: |
          (
            redis_memory_used_bytes /
            redis_memory_max_bytes
          ) * 100 > 90
        for: 2m
        labels:
          severity: warning
        annotations:
          summary: "High Redis memory usage"
          description: "Redis memory usage is {{ $value }}% on {{ $labels.instance }}"

      - alert: RedisHighConnections
        expr: redis_connected_clients > 100
        for: 2m
        labels:
          severity: warning
        annotations:
          summary: "High number of Redis connections"
          description: "{{ $value }} connections on Redis {{ $labels.instance }}"

      # Web server alerts
      - alert: NginxHighConnections
        expr: nginx_connections_active > 1000
        for: 2m
        labels:
          severity: warning
        annotations:
          summary: "High number of Nginx connections"
          description: "{{ $value }} active connections on {{ $labels.instance }}"

      - alert: PHPFPMHighLoad
        expr: phpfpm_active_processes / phpfpm_max_children > 0.8
        for: 2m
        labels:
          severity: warning
        annotations:
          summary: "PHP-FPM pool is under high load"
          description: "{{ $value | humanizePercentage }} of PHP-FPM processes are active on {{ $labels.instance }}"

      # Application-specific alerts
      - alert: HighResponseTime
        expr: histogram_quantile(0.95, rate(http_request_duration_seconds_bucket[5m])) > 2
        for: 2m
        labels:
          severity: warning
        annotations:
          summary: "High response time"
          description: "95th percentile response time is {{ $value }}s"

      - alert: FileUploadErrors
        expr: rate(file_upload_errors_total[5m]) > 1
        for: 1m
        labels:
          severity: warning
        annotations:
          summary: "High file upload error rate"
          description: "{{ $value }} file upload errors per second"

      - alert: SearchIndexingErrors
        expr: rate(search_indexing_errors_total[5m]) > 0.1
        for: 2m
        labels:
          severity: warning
        annotations:
          summary: "Search indexing errors detected"
          description: "{{ $value }} search indexing errors per second"

      # SSL certificate alerts
      - alert: SSLCertificateExpiry
        expr: probe_ssl_earliest_cert_expiry - time() < 86400 * 7
        for: 1m
        labels:
          severity: warning
        annotations:
          summary: "SSL certificate expiring soon"
          description: "SSL certificate for {{ $labels.instance }} expires in {{ $value | humanizeDuration }}"

      - alert: SSLCertificateExpired
        expr: probe_ssl_earliest_cert_expiry - time() <= 0
        for: 1m
        labels:
          severity: critical
        annotations:
          summary: "SSL certificate expired"
          description: "SSL certificate for {{ $labels.instance }} has expired"

      # Elasticsearch alerts
      - alert: ElasticsearchDown
        expr: elasticsearch_cluster_health_up == 0
        for: 1m
        labels:
          severity: critical
        annotations:
          summary: "Elasticsearch is down"
          description: "Elasticsearch cluster is down for more than 1 minute"

      - alert: ElasticsearchClusterRed
        expr: elasticsearch_cluster_health_status{color="red"} == 1
        for: 1m
        labels:
          severity: critical
        annotations:
          summary: "Elasticsearch cluster status is red"
          description: "Elasticsearch cluster health is RED"

      - alert: ElasticsearchClusterYellow
        expr: elasticsearch_cluster_health_status{color="yellow"} == 1
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "Elasticsearch cluster status is yellow"
          description: "Elasticsearch cluster health is YELLOW for more than 5 minutes"